---
product: "1.0.0"
info:
  name: "productservicedev"
  title: "ProductService_DEV"
  version: "1.0.0"
visibility:
  view:
    enabled: true
    type: "public"
    tags: []
    orgs: []
  subscribe:
    enabled: true
    type: "authenticated"
    tags: []
    orgs: []
apis:
  orderservice:
    $ref: "orderservice_2.0.0.yaml"
  productservice:
    $ref: "productservice_1.0.0.yaml"
  getinventory:
    $ref: "getinventory_1.0.0.yaml"
  getproductdetails:
    $ref: "getproductdetails_1.0.0.yaml"
plans:
  default:
    title: "Default Plan"
    description: "Default Plan"
    approval: false
    rate-limit:
      hard-limit: false
      value: "100/hour"
