---
swagger: "2.0"
info:
  x-ibm-name: "customerping"
  title: "CustomerPing"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/Customers"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    in: "query"
    name: "client_id"
security:
- clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - set-variable:
        title: "set-variable"
        actions:
        - set: "message.body"
          value: "{   \"Status\": \"Success\",   \"Description\": \"Successful Ping\"\
            \ }"
        version: "1.0.0"
  phase: "realized"
  catalogs:
    PROD: {}
    QA: {}
    Sandbox: {}
    QA2: {}
paths:
  /ping:
    get:
      responses:
        200:
          description: "200 OK"
definitions: {}
tags: []
