---
swagger: "2.0"
info:
  x-ibm-name: "eventnotifications"
  title: "EventNotifications"
  version: "1.0.0"
  contact:
    name: "Sujai Priyan"
    email: "sjaganathan@coach.com"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/"
consumes:
- "application/xml"
produces:
- "application/xml"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    in: "query"
    name: "client_id"
security:
- clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        target-url: "$(APIC_SG_DP_URL)"
        timeout: 60
        verb: "POST"
        cache-response: "protocol"
        cache-ttl: 900
  phase: "realized"
  properties:
    APIC_SG_DP_URL:
      value: ""
      description: ""
      encoded: false
  catalogs:
    QA:
      properties:
        APIC_SG_DP_URL: "http://cap-sg-prd-1.securegateway.appdomain.cloud:18598/Eventnotifications"
    Sandbox:
      properties:
        APIC_SG_DP_URL: "http://cap-sg-prd-2.securegateway.appdomain.cloud:18686/Eventnotifications"
    QA2:
      properties:
        APIC_SG_DP_URL: "http://cap-sg-prd-1.securegateway.appdomain.cloud:18593/Eventnotifications"
paths:
  /Eventnotifications:
    post:
      responses:
        200:
          description: "200 OK"
definitions: {}
tags: []
