---
swagger: "2.0"
info:
  x-ibm-name: "inventoryreservationretry"
  title: "InventoryReservation_Retry"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    in: "query"
    name: "client_id"
security:
- clientIdHeader: []
x-ibm-configuration:
  testable: false
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: "retryInvoke"
        timeout: 60
        verb: "POST"
        cache-response: "protocol"
        cache-ttl: 900
        stop-on-error:
        - null
        version: "1.0.0"
        tls-profile: "dev-oms"
        target-url: "$(OMS_Url)"
        username: "$(OMS_Username)"
        password: "QA_User"
  phase: "realized"
  properties:
    OMS_Password:
      value: ""
      description: "Password for OMS service used for Basic Authentication"
      encoded: false
    OMS_Username:
      value: ""
      description: "Username for OMS service used for Basic Authentication"
      encoded: false
    OMS_Url:
      value: ""
      description: ""
      encoded: false
  catalogs:
    Sandbox:
      properties:
        OMS_Url: "https://dev-oms.tapestry.com:444/smcfs/restapi/executeFlow/TPR_ReserveInventory"
        OMS_Username: "omsdev3"
        OMS_Password: "omsdev3"
    QA:
      properties:
        OMS_Password: "QA_User"
        OMS_Username: "QA_User"
        OMS_Url: "https://qa2-oms.tapestry.com:444/smcfs/restapi/executeFlow/TPR_ReserveInventory"
    QA2:
      properties:
        OMS_Url: "https://preprod-oms.tapestry.com:444/smcfs/restapi/executeFlow/TPR_ReserveInventory"
        OMS_Username: "PreProd_User"
        OMS_Password: "password"
    PROD:
      properties:
        OMS_Password: "Tapestry@123"
        OMS_Username: "OMS_MW_USER"
        OMS_Url: "https://prod-oms.tapestry.com:444/smcfs/restapi/executeFlow/TPR_ReserveInventory"
paths:
  /Inventoryreservationretry:
    post:
      responses:
        200:
          description: "200 OK"
      parameters:
      - name: "Body"
        required: false
        in: "body"
        schema:
          type: "object"
        description: "Request"
definitions: {}
tags: []
consumes:
- "application/xml"
basePath: "/"
produces:
- "application/xml"
