---
swagger: "2.0"
info:
  x-ibm-name: "masterskulist"
  title: "MasterSkuList"
  version: "1.0.0"
  contact:
    name: "Sathyanarayanan"
    email: "slakshmanan@coach.com"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/master"
consumes:
- "application/xml"
produces:
- "application/xml"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Id"
security:
- clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        target-url: "http://cap-sg-prd-1.securegateway.appdomain.cloud:18593/master/skulist"
        timeout: 60
        verb: "POST"
        cache-response: "no-cache"
        cache-ttl: 895
        stop-on-error: []
  phase: "realized"
paths:
  /skulist:
    post:
      responses:
        200:
          description: "200 OK"
      parameters:
      - name: "Body"
        required: true
        in: "body"
        schema:
          type: "object"
        description: "Required"
definitions: {}
tags: []
