---
swagger: "2.0"
info:
  x-ibm-name: "possessionmanagement"
  title: "POSSessionManagement"
  version: "1.0.0"
  contact:
    name: "Sathyanarayanan"
    email: "slakshmanan@coach.com"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/"
consumes:
- "application/xml"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    in: "query"
    name: "client_id"
security:
- clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: "invoke"
        timeout: 60
        verb: "POST"
        cache-response: "no-cache"
        cache-ttl: 60
        stop-on-error: []
        version: "1.0.0"
        target-url: "http://cap-sg-prd-1.securegateway.appdomain.cloud:18593/POSSessionManagement"
  phase: "realized"
paths:
  /POSSessionManagement:
    post:
      responses:
        200:
          description: "200 OK"
definitions: {}
tags: []
produces:
- "application/xml"
