---
swagger: "2.0"
info:
  x-ibm-name: "triggeremailsfmc"
  title: "TriggerEmailSFMC"
  version: "1.0.0"
  contact:
    name: "Sujai Priyan"
    email: "sjaganathan@coach.com"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Id"
security:
- clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        target-url: "$(APIC_SG_DP_URL)"
        timeout: 60
        verb: "POST"
        cache-response: "protocol"
        cache-ttl: 900
        stop-on-error: []
  phase: "realized"
  properties:
    APIC_SG_DP_URL:
      value: ""
      description: ""
      encoded: false
  catalogs:
    Sandbox:
      properties:
        APIC_SG_DP_URL: "http://cap-sg-prd-2.securegateway.appdomain.cloud:18686/TriggerEmailSFMC"
    QA2:
      properties:
        APIC_SG_DP_URL: "http://cap-sg-prd-1.securegateway.appdomain.cloud:18593/TriggerEmailSFMC"
    QA:
      properties:
        APIC_SG_DP_URL: "http://cap-sg-prd-1.securegateway.appdomain.cloud:18598/TriggerEmailSFMC"
    PROD:
      properties:
        APIC_SG_DP_URL: "http://cap-sg-prd-5.securegateway.appdomain.cloud:18999/TriggerEmailSFMC"
paths:
  /WelcomEmail:
    post:
      responses:
        200:
          description: "200 OK"
      parameters:
      - name: "Body"
        required: false
        in: "body"
        description: ""
        schema:
          type: "object"
definitions: {}
tags: []
