---
swagger: "2.0"
info:
  x-ibm-name: "vertex"
  title: "Vertex"
  version: "1.0.0"
  description: "Vertex tax services - This services needs to be integrated with an\
    \ application deployed in AWS and used in coach NA outlet stores ( in-store price\
    \ check app)."
  contact:
    name: "Sujai Priyan"
    email: "sjaganathan@coach.com"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/vertex"
consumes:
- "application/xml"
produces:
- "application/xml"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Id"
security:
- clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        target-url: "http://cap-sg-prd-1.securegateway.appdomain.cloud:18593/Vertex"
        verb: "POST"
        cache-response: "protocol"
        timeout: 60
        title: "invoke"
        cache-ttl: 900
  phase: "realized"
  gateway: "datapower-gateway"
paths:
  /CalculateTax:
    post:
      responses:
        200:
          description: "200 OK"
      parameters:
      - name: "Body"
        required: false
        in: "body"
        schema:
          type: "object"
definitions: {}
tags: []
